# Generated by Django 4.2.7 on 2025-10-06 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='passports/')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('lga', models.CharField(blank=True, max_length=100)),
                ('state_of_origin', models.CharField(blank=True, max_length=100)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('guardian_address', models.TextField(blank=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100)),
                ('section_a_completed', models.BooleanField(default=False)),
                ('section_b_completed', models.BooleanField(default=False)),
                ('section_c_completed', models.BooleanField(default=False)),
                ('section_d_completed', models.BooleanField(default=False)),
                ('section_e_completed', models.BooleanField(default=False)),
                ('first_choice', models.CharField(blank=True, choices=[('diploma_schew', 'Diploma in Community Health (SCHEW)'), ('certificate_jchew', 'Certificate in Community Health (JCHEW)'), ('diploma_him', 'Diploma in Health Information Management'), ('diploma_env_health', 'Diploma in Environmental Health'), ('diploma_xray', 'Diploma in X-Ray and Imaging'), ('diploma_nutrition', 'Diploma in Nutrition and Dietetics'), ('retraining_jchew', 'Retraining in Community Health (JCHEW holders)')], max_length=50)),
                ('second_choice', models.CharField(blank=True, choices=[('diploma_schew', 'Diploma in Community Health (SCHEW)'), ('certificate_jchew', 'Certificate in Community Health (JCHEW)'), ('diploma_him', 'Diploma in Health Information Management'), ('diploma_env_health', 'Diploma in Environmental Health'), ('diploma_xray', 'Diploma in X-Ray and Imaging'), ('diploma_nutrition', 'Diploma in Nutrition and Dietetics'), ('retraining_jchew', 'Retraining in Community Health (JCHEW holders)')], max_length=50)),
                ('declaration_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ssce', 'SSCE Results'), ('primary', 'Primary School Certificate'), ('indigene', 'Indigene Certificate'), ('birth', 'Birth Certificate/Declaration of Age'), ('other', 'Other Credentials')], max_length=20)),
                ('document_file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='portal.application')),
            ],
            options={
                'verbose_name': 'Uploaded Document',
                'verbose_name_plural': 'Uploaded Documents',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('has_paid', models.BooleanField(default=False)),
                ('used_referral', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referral_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.referralcode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='SSCEResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(blank=True, choices=[('waec', 'WAEC'), ('neco', 'NECO'), ('nabteb', 'NABTEB'), ('nbais', 'NBAIS')], max_length=20)),
                ('exam_number', models.CharField(blank=True, max_length=50)),
                ('centre_number', models.CharField(blank=True, max_length=50)),
                ('centre_name', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('awaiting_result', models.BooleanField(default=False)),
                ('english', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('mathematics', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('biology', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('chemistry', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('physics', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_6', models.CharField(blank=True, max_length=100)),
                ('grade_6', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_7', models.CharField(blank=True, max_length=100)),
                ('grade_7', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_8', models.CharField(blank=True, max_length=100)),
                ('grade_8', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('subject_9', models.CharField(blank=True, max_length=100)),
                ('grade_9', models.CharField(blank=True, choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssce_results', to='portal.application')),
            ],
            options={
                'verbose_name': 'SSCE Result',
                'verbose_name_plural': 'SSCE Results',
            },
        ),
        migrations.CreateModel(
            name='SchoolAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('from_year', models.CharField(blank=True, max_length=4)),
                ('to_year', models.CharField(blank=True, max_length=4)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools_attended', to='portal.application')),
            ],
            options={
                'verbose_name': 'School Attended',
                'verbose_name_plural': 'Schools Attended',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('paystack_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='portal.student')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='portal.student'),
        ),
    ]
