# Generated by Django 4.2.7 on 2026-08-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_siteconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='first_choice',
            field=models.CharField(blank=True, choices=[('certificate_jchew', 'Certificate in Community Health (JCHEW)'), ('diploma_dental_surgery', 'Diploma in Dental Surgery'), ('diploma_schew', 'Diploma in Community Health'), ('diploma_env_health', 'Diploma in Environmental Health Technology'), ('diploma_xray', 'Diploma in Medical Imaging Technology'), ('diploma_medical_lab', 'Diploma in Medical Laboratory'), ('diploma_nutrition', 'Diploma in Nutrition and Dietetics'), ('nd_community_health', 'National Diploma in Community Health'), ('retraining_jchew', 'Retraining in Community Health (JCHEW holders)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='second_choice',
            field=models.CharField(blank=True, choices=[('certificate_jchew', 'Certificate in Community Health (JCHEW)'), ('diploma_dental_surgery', 'Diploma in Dental Surgery'), ('diploma_schew', 'Diploma in Community Health'), ('diploma_env_health', 'Diploma in Environmental Health Technology'), ('diploma_xray', 'Diploma in Medical Imaging Technology'), ('diploma_medical_lab', 'Diploma in Medical Laboratory'), ('diploma_nutrition', 'Diploma in Nutrition and Dietetics'), ('nd_community_health', 'National Diploma in Community Health'), ('retraining_jchew', 'Retraining in Community Health (JCHEW holders)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=12500, help_text='Amount (₦) charged to applicants for the application form/payment.', max_digits=10),
        ),
    ]
